#!/bin/bash

#validate yaml
#/bbx/bin/biobox-validator/validate-input --schema=/bbx/schema/schema.yaml --input=/bbx/input/biobox.yaml

#if valid yaml run concoct command
if [ $? -eq 0 ]
then
    source activate snakemake 
    cd /bbx && pip freeze && /opt/miniconda/envs/snakemake/bin/python command_handler.py -i /bbx/input/biobox.yaml -o /bbx/output 2> /bbx/output/log.txt
else
    exit 1;
fi
